services:
  postgres:
    image: postgres:16
    container_name: content_manager_postgres
    restart: always
    environment:
      POSTGRES_USER: content_user
      POSTGRES_PASSWORD: content_pass
      POSTGRES_DB: content_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: